# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestEditor' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestEditor
  pod 'MarkdownView'
  pod 'SwiftyAttributes'
  pod 'DynamicColor'
#  pod 'Hop', :git => 'https://github.com/OMTS/Hop.git', :branch => 'develop'
  pod 'Hop', :git => 'https://github.com/OMTS/Hop.git', :branch => 'feature-environment-configuration'

  target 'TestEditorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestEditorUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
